[Refactor][챌린지/온보딩] 디자인 수정
CCC-org/keewe-app pull request #51
Opened 2022-10-16 06:21 UTC by watchiswatch

## Refactor
* 챌린지 및 온보딩 자잘한 UI 수정

2022-10-21 01:54 UTC, akdlsz21 commented
Conflict 해결해주실수 있으실까요?

2022-10-21 01:55 UTC, akdlsz21 requested changes
need conflict resolve

2022-10-22 14:10 UTC, ysh4296 reviewed
conflict 확인해주세요!

2022-11-06 14:52 UTC, ysh4296 reviewed
코멘트 확인해주세요

2022-11-06 14:52 UTC, ysh4296 commented on src/screens/onboarding/ServiceIntroTwoScreen.tsx
> +createStyle();
이거 어디에 쓰는거죠?

2022-11-07 09:52 UTC, watchiswatch commented on src/screens/onboarding/ServiceIntroTwoScreen.tsx
> +createStyle();
불 필요한 부분입니다, 지우겠습니다.

2022-11-08 16:59 UTC, ysh4296 approved these changes

2022-11-13 04:43 UTC, merged